server:
  port: 8081

spring:
  datasource:
#    url: jdbc:mysql://192.168.152.161:3306/qunzhi-db?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/qunzhi-db?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: localhost
#    host: 192.168.152.161
    port: 6379
    database: 0
#    password: redis

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
