server:
  port: 8888

spring:
  redis:
    host: localhost
    port: 6379
    database: 0

  #分库分表
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://222.25.188.1:43792/qunzhi-db?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://222.25.188.1:49567/qunzhi-db2?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
    sharding:
      tables:
        user:
          # 配置主键生成策略,props中指定雪花算法的配置
          key-generator:
            column: id
            type: SNOWFLAKE
            props:
              work:
                id: 345
              max:
                tolerate:
                  time:
                    difference:
                      milliseconds: 10
          actual-data-nodes: ds0.user_$->{1..2}
          table-strategy:
            standard:
              sharding-column: id
              precise-algorithm-class-name: com.xidian.qunzhi.config.MySharding

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
