server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qunzhi-db?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
