server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://222.25.188.1:31210/iotdata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xidian@123

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/*.xml

jwt:
  tokenHead: 'btc'
  tokenHeader: 'Authorization'
  secret: suo-ran-wu-wei-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)

