server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://222.25.188.1:31210/iotdata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: xidian@123

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/*.xml

