server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://222.25.188.1:31206/iotdata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    #url: jdbc:mysql://localhost:3306/iotdata?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: xidian@123
    #password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:mapper/*.xml


